"""Add Status field

Revision ID: 4161ddbf2286
Revises: 1981b6ab8a24
Create Date: 2025-01-06 11:42:52.568299

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4161ddbf2286'
down_revision = '1981b6ab8a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservationmodel', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservationmodel', 'status')
    # ### end Alembic commands ###
