"""Create Room and Seat tables

Revision ID: 443438f7a928
Revises: 7b7b939a117d
Create Date: 2024-10-09 21:17:04.106811

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '443438f7a928'
down_revision = '7b7b939a117d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roommodel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seatmodel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['roommodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seatmodel')
    op.drop_table('roommodel')
    # ### end Alembic commands ###
