"""Add created_at for reservation

Revision ID: 60f0682fd70f
Revises: 88b07e8c8fe8
Create Date: 2024-10-14 23:23:15.698223

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '60f0682fd70f'
down_revision = '88b07e8c8fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservationmodel', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservationmodel', 'created_at')
    # ### end Alembic commands ###
