"""Create Showtime table

Revision ID: 7b7b939a117d
Revises: ca34ab7c74be
Create Date: 2024-08-30 23:28:23.971247

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7b7b939a117d'
down_revision = 'ca34ab7c74be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showtimemodel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('show_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['moviemodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showtimemodel')
    # ### end Alembic commands ###
