"""Remove status choices

Revision ID: ac456404261c
Revises: 8a3d7fc2595c
Create Date: 2024-10-12 18:59:07.342201

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac456404261c'
down_revision = '8a3d7fc2595c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seatmodel', 'status',
               existing_type=postgresql.ENUM('AVAILABLE', 'RESERVED', 'OCCUPIED', name='seatstatus'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seatmodel', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('AVAILABLE', 'RESERVED', 'OCCUPIED', name='seatstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
