"""Add Provider payment id field

Revision ID: b34457d0cedd
Revises: 569fcfafc8de
Create Date: 2025-01-20 17:25:09.577522

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b34457d0cedd'
down_revision = '569fcfafc8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservationmodel', sa.Column('provider_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservationmodel', 'provider_payment_id')
    # ### end Alembic commands ###
