"""Create Category table

Revision ID: ca34ab7c74be
Revises: dd6e2f0f41bd
Create Date: 2024-08-25 08:21:29.515211

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ca34ab7c74be'
down_revision = 'dd6e2f0f41bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorymodel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moviecategorylink',
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categorymodel.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['moviemodel.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moviecategorylink')
    op.drop_table('categorymodel')
    # ### end Alembic commands ###
