"""Create Genre table

Revision ID: ca34ab7c74be
Revises: dd6e2f0f41bd
Create Date: 2024-08-25 08:21:29.515211

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ca34ab7c74be'
down_revision = 'dd6e2f0f41bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genremodel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moviegenrelink',
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genremodel.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['moviemodel.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moviegenrelink')
    op.drop_table('genremodel')
    # ### end Alembic commands ###
