"""Create Seat table

Revision ID: dab605a77cf4
Revises: 37766fdac85c
Create Date: 2024-10-09 23:34:02.184552

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dab605a77cf4'
down_revision = '37766fdac85c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seatmodel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'OCCUPIED', name='seatstatus'), nullable=False),
    sa.Column('showtime_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimemodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seatmodel')
    # ### end Alembic commands ###
