from typing import Protocol

from app.reservations.domain.collections.seats import Seats
from app.reservations.domain.movie_reservation import MovieReservation
from app.reservations.domain.reservation import Reservation
from app.shared.domain.value_objects.id import ID


class ReservationRepository(Protocol):
    def create(self, reservation: Reservation) -> None: ...
    def find_seats(self, seat_ids: list[ID]) -> Seats: ...
    def get(self, reservation_id: ID) -> Reservation: ...
    def release(self, reservation_id: ID) -> None: ...
    def find_by_user_id(self, user_id: ID) -> list[MovieReservation]: ...
