from typing import Protocol
from uuid import UUID

from app.reservations.domain.collections.seats import Seats
from app.reservations.domain.reservation import Reservation


class ReservationRepository(Protocol):
    def create(self, reservation: Reservation) -> None: ...
    def find_seats(self, seat_ids: list[UUID]) -> Seats: ...
    def get(self, reservation_id: UUID) -> Reservation: ...
    def release(self, reservation_id: UUID) -> None: ...
