from datetime import date
from typing import Protocol

from app.movies.domain.movie import Movie
from app.shared.domain.value_objects.id import Id


class MovieRepository(Protocol):
    def save(self, movie: Movie) -> None: ...

    def get(self, id: Id) -> Movie | None: ...

    def delete(self, id: Id) -> None: ...

    def add_genre(self, movie_id: Id, genre_id: Id) -> None: ...

    def remove_genre(self, movie_id: Id, genre_id: Id) -> None: ...

    def get_available_movies_for_date(self, available_date: date) -> list[Movie]: ...

    def get_movie_for_date(self, movie_id: Id, showtime_date: date) -> Movie | None: ...
