from datetime import date
from typing import Protocol

from app.movies.domain.movie import Movie
from app.shared.domain.value_objects.id import ID


class MovieRepository(Protocol):
    def save(self, movie: Movie) -> None: ...

    def get(self, id: ID) -> Movie | None: ...

    def delete(self, id: ID) -> None: ...

    def add_genre(self, movie_id: ID, genre_id: ID) -> None: ...

    def remove_genre(self, movie_id: ID, genre_id: ID) -> None: ...

    def get_available_movies_for_date(self, available_date: date) -> list[Movie]: ...

    def get_movie_for_date(self, movie_id: ID, showtime_date: date) -> Movie | None: ...
