name: CI

on:
  pull_request:
    branches: ["master"]

  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Check code quality
        run: |
          poetry run mypy app
          poetry run ruff check app
          poetry run ruff format app --check

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and test Docker image
        env:
          DOMAIN: example.com
          STACK_NAME: movie-system-reservation
          POSTGRES_PASSWORD: testpassword
          POSTGRES_USER: testuser
          POSTGRES_DB: testdb
          SECRET_KEY: testsecretkey
        run: |
          docker compose build
          docker compose up -d db
          docker compose up -d backend
          docker compose run backend pytest
          docker compose down -v

      - name: Run tests
        run: poetry run pytest

      - name: Check for database migrations
        run: poetry run alembic check
